### PR TITLE
Support for redis session 

### PR DESCRIPTION
**Pull request by ayoubeddafali**
Add support for redis session

### CODE REVIEW

**Comment by fballiano** [comment]
is this redis directly started on every apache instance? if so

**Comment by ayoubeddafali** [comment]
Yes, the module is activated by default in all apache containers ( docker-php-ext-enable redis) , but it is deactivated in the php.ini so, if you  want to use it, you need to uncomment the two lines related to redis, and add redis to the app/local/local.xml config file. 
If we will always use redis for session, we can add the configuration in start.sh or in another script in ENTYRPOINT

**Comment by fballiano** [comment]
wouldn’t it be better to use the same mecanism already used for the magento
cache? spin another container for all the swarm/cluster instead of heaving
it on every container

**Comment by ayoubeddafali** [comment]
Yes, that's actually what I said. 
There will be a redis container for sessions, and the above config is just a module that help the apache containers to connect with the redis instance. 
Here is an example I did for magento 1 in the apache containers, I've added an ENTRYPOINT script that change the config in the local.xml file, like so : 
```bash
sed -i "/<global>/ a\\
 <session_save>db</session_save> \\
	<redis_session> \\
	<host>redis</host> \\
	<port>6379</port> \\
	<password></password> \\
	<timeout>10</timeout> \\
	<persistent></persistent> \\
	<db>1</db> \\
	<compression_threshold>2048</compression_threshold> \\
	<compression_lib>gzip</compression_lib> \\
	<log_level>1</log_level> \\
	<max_concurrency>64</max_concurrency> \\
	<break_after_frontend>5</break_after_frontend> \\
	<break_after_adminhtml>30</break_after_adminhtml> \\
	<first_lifetime>600</first_lifetime> \\
	<bot_first_lifetime>60</bot_first_lifetime> \\
	<bot_lifetime>7200</bot_lifetime> \\
	<disable_locking>0</disable_locking> \\
	<min_lifetime>86400</min_lifetime> \\
	<max_lifetime>2592000</max_lifetime> \\
    </redis_session> \\
    <cache> \\
        <backend>Cm_Cache_Backend_Redis</backend> \\
        <backend_options> \\
          <default_priority>10</default_priority> \\
          <auto_refresh_fast_cache>1</auto_refresh_fast_cache> \\
            <server>redis-cache</server> \\
            <port>6379</port> \\
            <persistent></persistent> \\
            <database>1</database> \\
            <password></password> \\
            <force_standalone>0</force_standalone> \\
            <connect_retries>1</connect_retries> \\
            <read_timeout>10</read_timeout> \\
            <automatic_cleaning_factor>0</automatic_cleaning_factor> \\
            <compress_data>1</compress_data> \\
            <compress_tags>1</compress_tags> \\
            <compress_threshold>20480</compress_threshold> \\
            <compression_lib>gzip</compression_lib> \\
        </backend_options> \\
    </cache>" /var/www/html/app/etc/local.xml
  
sed -i "s/false/true/" /var/www/html/app/etc/modules/Cm_RedisSession.xml

```

and in the docker-compose file, we would have this service added : 
```bash
  redis: 
    image: redis
    networks:
      - appnet 
```

**Pull request closed without merging**
